# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\p214s\OneDrive\Documents\GitHub\Team_X_ECE_1140\track_controller\sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UserName_TextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.UserName_TextBox.setGeometry(QtCore.QRect(210, 90, 431, 64))
        self.UserName_TextBox.setObjectName("UserName_TextBox")
        self.Password_TextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Password_TextBox.setGeometry(QtCore.QRect(210, 180, 431, 64))
        self.Password_TextBox.setObjectName("Password_TextBox")
        self.UserName_label = QtWidgets.QLabel(self.centralwidget)
        self.UserName_label.setGeometry(QtCore.QRect(60, 90, 141, 51))
        self.UserName_label.setObjectName("UserName_label")
        self.Password_Label = QtWidgets.QLabel(self.centralwidget)
        self.Password_Label.setGeometry(QtCore.QRect(60, 190, 131, 51))
        self.Password_Label.setObjectName("Password_Label")
        self.SignInButton = QtWidgets.QPushButton(self.centralwidget)
        self.SignInButton.setGeometry(QtCore.QRect(410, 300, 231, 71))
        self.SignInButton.setObjectName("SignInButton")
        self.Track_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Track_comboBox.setGeometry(QtCore.QRect(370, 11, 281, 51))
        self.Track_comboBox.setObjectName("Track_comboBox")
        self.TrackSelection_Label = QtWidgets.QLabel(self.centralwidget)
        self.TrackSelection_Label.setGeometry(QtCore.QRect(70, 20, 291, 21))
        self.TrackSelection_Label.setObjectName("TrackSelection_Label")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(60, 260, 581, 31))
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UserName_label.setText(_translate("MainWindow", "Username:"))
        self.Password_Label.setText(_translate("MainWindow", "Password:"))
        self.SignInButton.setText(_translate("MainWindow", "Sign In"))
        self.TrackSelection_Label.setText(_translate("MainWindow", "Track Selection"))
        self.error_label.setText(_translate("MainWindow", " "))
